export { default as Profile } from './Profile'
export { default as DashBoard } from './DashBoard'
export { default as WishList } from './WishList'
// ui
export { default as ProfileMobile } from './ui/mobile/ProfileMobileUi'
export { default as ProfileDesktop } from './ui/desktop/ProfileDesktopUi'
export { default as GenresTagMobileUi } from './ui/mobile/GenresTagMobileUi'
export { default as GenresTagDesktopUi } from './ui/desktop/GenresTagDesktopUi'
export { default as EditProfileImageUi } from './ui/EditProfileImageUi'
export { default as ProfileImageUi } from './ui/ProfileImageUi'
export { default as ProfileBackgroundUi } from './ui/ProfileBackgroundUi'
export { default as DashBoardCardUi } from './ui/DashBoardCardUi'
export { default as InfoBox } from './user-info/user-delete/InfoBox'
export { default as UserDeleteClient } from './user-info/user-delete/UserDeleteClient'
export { default as WishListCarouselNavUi } from './ui/WishListCarouselNavUi'
export { default as WishListCarouselUi } from './ui/WishListCarouselUi'
export { default as WishListEmptyUi } from './ui/WishListEmptyUi'
export { default as WishListTitleUi } from './ui/WishListTitleUi'
