export const PLAYTYPE_LABELS = {
  prefix: {
    immersive: '몰입형',
    intense: '열정적인',
    peaceful: '평화로운',
    healing: '힐링',
    strategic: '전략적인',
    challenging: '도전적인',
    casual: '캐주얼',
    horror: '스릴러',
    fantasy: '판타지',
    creative: '창작형',
    retro: '레트로',
    scifi: 'SF',
    emotional: '감성적인',
    realistic: '리얼리스트',
    anime: '애니메이션',
    apocalypse: '서바이벌',
    historical: '역사',
    modern: '현대적인',
  } as Record<string, string>,

  middle: {
    story: '스토리',
    action: '액션',
    character: '캐릭터',
    visual: '감성',
    freedom: '자유',
    fast: '스피드',
    puzzle: '퍼즐',
    collector: '수집형',
    arcade: '아케이드',
    audio: '사운드',
  } as Record<string, string>,

  suffix: {
    solo: '탐험가',
    social: '소셜러',
    competitive: '도전자',
    cooperative: '협력가',
    explorer: '모험가',
    strategic: '전략가',
    immersive: '몰입러',
    healing: '힐러',
    creative: '크리에이터',
    collector: '컬렉터',
    challenging: '정복자',
  } as Record<string, string>,
}
