export const PLAYTYPE_EMOJI: Record<string, string> = {
  solo: '🎮',
  social: '👥',
  cooperative: '🤝',
  competitive: '🥇',
  story: '📖',
  immersive: '🔥',
  casual: '☕',
  challenging: '🏆',
  healing: '💚',
  intense: '⚡',
  action: '⚔️',
  strategic: '🧠',
  puzzle: '🧩',
  explorer: '🧭',
  collector: '💎',
  creative: '🎨',
  visual: '✨',
  retro: '👾',
  anime: '🌸',
  audio: '🎵',
  realistic: '🎬',
  fantasy: '🐉',
  scifi: '🚀',
  modern: '🏙️',
  historical: '⚔️',
  apocalypse: '☢️',
  freedom: '🌍',
  fast: '💨',
  peaceful: '🌿',
  emotional: '🥹',
  horror: '👻',
  character: '💕',
  arcade: '🕹️',
}
