import { Suspense } from 'react'

import { Header } from '@/components/layout'
import Providers from '@/components/providers/Providers'

import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <Suspense>
            <Header />
          </Suspense>
          {children}
        </Providers>
      </body>
    </html>
  )
}
