import { Suspense } from 'react'

import { Header } from '@/components/layout'

import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <Header />
        </Suspense>
        {children}
      </body>
    </html>
  )
}
